import { router, json, error, requireAuth, withScopes, ai } from '@appdeploy/sdk';
import { db } from '@appdeploy/sdk';
import { TABLES, ensureCatalogSeed, getOrCreateProfile, listPublishedProducts } from './data';

const ADMIN_EMAILS=['t.riyad.2k9@gmail.com'];
const requireAdmin=()=>async(ctx:{user?:{email?:string}})=>ADMIN_EMAILS.includes(ctx.user?.email?.toLowerCase()||'')?undefined:error('Admin access denied',403);
export const handler=router({
 'GET /api/_healthcheck':[async()=>json({ok:true,service:'digital-products-store'})],
 'GET /api/products':[async()=>{await ensureCatalogSeed();return json({products:await listPublishedProducts()});}],
 'GET /api/me':[requireAuth(),async ctx=>json({user:ctx.user,profile:await getOrCreateProfile(ctx.user!.userId,ctx.user!.email,ctx.user!.name)})],
 'GET /api/customer/dashboard':[requireAuth(),async ctx=>{const o=await db.list(TABLES.orders,{filter:{user_id:ctx.user!.userId},limit:100});const w=await db.list(TABLES.wallets,{filter:{user_id:ctx.user!.userId},limit:1});return json({orders:o.items,wallet:w.items[0]?.balance||0});}],
 'POST /api/orders':[requireAuth(),async ctx=>{const b=(ctx.body||{}) as {items?:unknown[];total?:number;wallet_amount?:number;external_amount?:number;payment_method?:string;transaction_id?:string};if(!Array.isArray(b.items)||typeof b.total!=='number'||b.total<=0||!b.transaction_id)return error('Items, valid total and transaction ID are required',400);const [id]=await db.add(TABLES.orders,[{user_id:ctx.user!.userId,items:b.items,total:b.total,wallet_amount:Math.max(0,b.wallet_amount||0),external_amount:Math.max(0,b.external_amount||0),payment_method:b.payment_method||'manual',transaction_id:b.transaction_id,status:'payment_verification_pending',fulfillment_status:'awaiting_payment',created_at:Date.now()}]);if(!id)return error('Could not create order',500);await db.add(TABLES.payments,[{order_id:id,user_id:ctx.user!.userId,method:b.payment_method||'manual',transaction_id:b.transaction_id,amount:b.external_amount||0,status:'pending',created_at:Date.now()}]);return json({order_id:id},201)}],
 'POST /api/ai-support':[requireAuth(),async ctx=>{const b=(ctx.body||{}) as {question?:string};if(!b.question?.trim())return error('Question required',400);const r=await ai.generate({system:'Answer only store FAQ, product information, basic order status, warranty and refund policy. For anything outside those topics, say a support agent will take over. Never change payments, wallets, refunds, or reveal credentials.',prompt:b.question,maxTokens:250,thinkingMode:'FAST'});return json({answer:r.text});}],
 'GET /api/admin/dashboard':[requireAuth(),withScopes('email'),requireAdmin(),async()=>{const p=await db.list(TABLES.products,{limit:100});const o=await db.list(TABLES.orders,{limit:100});const pay=await db.list(TABLES.payments,{limit:100});const c=await db.list(TABLES.profiles,{limit:100});return json({counts:{products:p.items.length,orders:o.items.length,payments:pay.items.length,customers:c.items.length}})}],
 'POST /api/admin/products':[requireAuth(),withScopes('email'),requireAdmin(),async ctx=>{const b=(ctx.body||{}) as Record<string,unknown>;if(typeof b.name!=='string'||!b.name.trim()||b.authorized_to_sell!==true)return error('Name and authorization are required',400);const [id]=await db.add(TABLES.products,[{...b,status:b.status||'draft',created_at:Date.now(),updated_at:Date.now()}]);return id?json({id},201):error('Could not create product',500)}]
});